language: python
python:
    - "2.7"
sudo: required
before_install:
    - sudo apt-get -qq update
    - sudo apt-get install libseccomp-dev cmake
install:
    - mkdir build && cd build
    - cmake .. && make && sudo make install
    - cd ../bindings/Python && sudo python setup.py install
script:
    - cd ../../tests/Python_and_core && sudo python test.py
notifications:
    slack: onlinejudgeteam:BzBz8UFgmS5crpiblof17K2W
